---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seancheey.
--- DateTime: 9/13/20 3:32 PM
---

PlayerInfo = {}
PlayerInfo.__index = PlayerInfo

--- @return LuaEntityPrototype[]
function PlayerInfo.unlocked_crafting_machines(player_index)
    local all_factory_list = newtable()
    for _, entity in pairs(game.get_filtered_entity_prototypes({
        { filter = "crafting-machine" },
        { filter = "hidden", invert = true, mode = "and" },
        { filter = "blueprintable", mode = "and" } })) do
        all_factory_list[#all_factory_list + 1] = entity
    end
    local unlocked_recipes = PlayerInfo.unlocked_recipes(player_index)

    local unlocked_factories = {}
    for _, factory in ipairs(all_factory_list) do
        for _, recipe in pairs(unlocked_recipes) do
            if Table.has(recipe.products, factory, function(a, b)
                return a.name == b.name
            end) then
                unlocked_factories[#unlocked_factories + 1] = factory
                break
            end
        end
    end
    return unlocked_factories
end

--- @return LuaEntityPrototype[]
function PlayerInfo.unlocked_belts(player_index)

end

--- @return LuaEntityPrototype[]
function PlayerInfo.unlocked_inserters(player_index)

end

--- @return LuaRecipePrototype[]
function PlayerInfo.unlocked_recipes(player_index)
    local unlocked_recipes = Table.filter(game.players[player_index].force.recipes, function(recipe)
        return not recipe.hidden and recipe.enabled
    end)
    return unlocked_recipes
end

--- @return LuaEntityPrototype[]
function PlayerInfo.crafting_machine_priorities(player_index)
    return global.settings[player_index].factory_priority
end