---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seancheey.
--- DateTime: 10/17/20 3:53 PM
---

local BlueprintGeneratorUtil = {}

--- @param crafting_item Product|Ingredient
--- @return number average amount
function BlueprintGeneratorUtil.average_amount_of(crafting_item)
    assert(crafting_item.amount or crafting_item.amount_max, serpent.line(crafting_item) .. "has no amount or amount_max field")
    return crafting_item.amount or ((crafting_item.amount_max + crafting_item.amount_min) / 2)
end

return BlueprintGeneratorUtil