---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seancheey.
--- DateTime: 10/17/20 3:53 PM
---

local BlueprintGeneratorUtil = {}

--- @param crafting_item Product|Ingredient
--- @return number average amount
function BlueprintGeneratorUtil.average_amount_of(crafting_item)
    assert(crafting_item.amount or crafting_item.amount_max, serpent.line(crafting_item) .. "has no amount or amount_max field")
    return crafting_item.amount or ((crafting_item.amount_max + crafting_item.amount_min) / 2)
end

--- @param recipe LuaRecipePrototype
--- @param crafter LuaEntityPrototype
--- @param inserterIngredientsMapping table<string, string[]> inserter's name to the ingredients it can grab
--- @return table<string, number> speed table of ingredient/product name to number of items crafted per sec
function BlueprintGeneratorUtil.calculateRecipeCraftingSpeed(recipe, crafter, inserterIngredientsMapping)

end

return BlueprintGeneratorUtil